site_name: Tutorial web pages
site_url: https://LamineTourelab.github.io/Tutorial
site_author: Lamine TOURE
site_description: A repository dedicated for education. Lets learn together 

repo_url: https://github.com/LamineTourelab/Tutorial
repo_name: GitHub
edit_uri: https://github.com/LamineTourelab/Tutorial/tree/main/docs

# docs_dir: sources
#theme:
#    name: null
#    custom_dir: 'custom_theme/'
theme: yeti



nav:
  - Home: index.md
  - Machine learning:
      - USER_GUIDE_INDEX.md