<<<<<<< HEAD
site_name: My Docs
=======
site_name: Tutorial web pages
>>>>>>> 54ef556e27424da7c3ee8414238fcd4cd106c002
site_url: https://LamineTourelab.github.io/Tutorial
site_author: Lamine TOURE
site_description: A repository dedicated for education. Lets learn together 

repo_url: https://github.com/LamineTourelab/Tutorial
repo_name: GitHub
edit_uri: https://github.com/LamineTourelab/Tutorial/tree/main/docs

#theme:
#    name: null
#    custom_dir: 'custom_theme/'
theme: yeti

markdown_extensions:
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - cinder/css/base.css
  - cinder/css/bootstrap.min.css
  - cinder/css/font-awesome.min.css

copyright: Copyright &copy; 2014-2023 <a href="https://sebastianraschka.com">Sebastian Raschka</a>
google_analytics: ['UA-38457794-2', 'LamineTourelab.github.io/Tutorial/']

nav:
  - Home: index.md
  - Machine learning:
      - USER_GUIDE_INDEX.md